### ISSUE TITLE
Tap-drag zooming is broken

### ISSUE THREAD

**Issue by brewin** [tomtom-international/maps-sdk-for-android-examples#14]
Tapping and dragging up/down should smoothly zoom the map, but it jumps rapidly between zoom levels. Most likely because the gesture is detected as a double-tap before the drag starts.

Edit: 
Actually double-tapping doesn't zoom the map at all, at least in the example app. Also, pinch-zoom rotates the map, which it shouldn't do. All the gestures seem a bit "off" compared to other map SDKs, which makes navigating the map very difficult.

**Comment by Flyentology** [comment]
Hey,

Double tapping issue was a bug that was fixed in version 2.4.617. 

> pinch-zoom rotates the map, which it shouldn't do. 
I would disagree that these gestures should be mutually exclusive. However right now the only thing you could do is to disable either the zoom or rotate gesture using GesturesConfiguration class and create your own logic to turn these gestures on and off.

If you think that SDK should give the ability to set mutually exclusive gestures feel free to respond. I will pass the idea to the team.

**Comment by brewin** [comment]
> Double tapping issue was a bug that was fixed in version 2.4.617.

Nice!

> I would disagree that these gestures should be mutually exclusive.

On Google Maps, a pinch zoom can follow an initial rotate gesture but not the other way around. A rotate gesture can't follow an initial pinch zoom. I think it's a good idea to replicate the Google Maps gestures, since that's what people are familiar with.

**Comment by Flyentology** [comment]
As the double tapping issue I was refering to this bit:

> Actually double-tapping doesn't zoom the map at all

I'm gonna report the tap-drag zooming issue to the team.

**Comment by MichalWlodarczyk2TomTom** [comment]
As mentioned in previous comments, there are no plans to implement support for mutually exclusive gestures. Therefore, closing an issue.
