### ISSUE TITLE
 Program type already present: com.google.gson.typeadapters.RuntimeTypeAdapterFactory

### ISSUE THREAD

**Issue by DashVirus** [tomtom-international/maps-sdk-for-android-examples#7]
Hi, 

"Program type already present: com.google.gson.gson.typeadapters.RuntimeTypeAdapterFactory"

After a few searches, it turns out that a class present in the dependencies used by the MapBox system has the same name as yours (RuntimeTypeAdapterFactory) but is not implemented in the same way.

I have already tried to exclude gson dependencies to prevent the clash 
It seems, if I am not mistaken, that Tomtom has an embedded version of gson which can not be excluded with Gradle. 

Could you help me solve this issue 

Thanks in advance,

**Comment by mwlodarczyk** [comment]
Indeed, we have the gson dependency inside the SDK. We use the 2.8.2 gson version. However, the 'RuntimeTypeAdapterFactory' is not served inside the gson library. 

It is available inside the gson-extras library. However, the sdk-maps module includes this source class directly instead of relying on gson-extras. Therefore, the exclude command does not work.

I will follow up to improve the sdk-maps package so it uses gson-extras instead of using the selected file.

**Comment by mwlodarczyk** [comment]
Hi @DashVirus,

The reported issue is fixed in 2.4.101. Please update the SDK and see if it is working for you now. Closing the issue for now.
